# Generated by Django 6.0.4 on 2026-06-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_status_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("accepted", "Accepted")],
                default="open",
                max_length=20,
            ),
        ),
    ]
